#!/bin/bash

# This script prepares a linux desktop environment for this first time by
# installing and configuring a bunch of commonly used applications. Before
# running it, you should read it, understand it, and tweak it as necessary.
# It is liable to fall out-of-date, and has some idiosyncatic configuration
# options that you might not want (such as setting vim as your default editor
# for git). It was tested with Linux Mint 18.2 (which is based on Ubuntu 16.04)
# on 9/19/2017. It should be relatively safe to run multiple times in a row,
# although some commands will fail if, for example, certain directories and
# programs already exist.
# Author: Nathan J Cochran

if (( $(id -u) == 0 )); then
	printf "Please do not run as root (script will prompt for root credentials when necessary)\n"
	exit 1
fi

printf "\n--------------------\n"
printf "Updating system packages"
printf "\n--------------------\n"
sudo apt-get update
sudo apt-get dist-upgrade			# Smarter than upgrade. Handles updating/removing dependencies

printf "\n--------------------\n"
printf "Installing vim"
printf "\n--------------------\n"
sudo add-apt-repository ppa:jonathonf/vim	# More up-to-date than the default provided by the software manager
sudo apt-get update
sudo apt-get install vim-gnome              # Gnome version is necessary for gvim/clipboard support

printf "\n--------------------\n"
printf "Installing git"
printf "\n--------------------\n"
sudo add-apt-repository ppa:git-core/ppa	# More up-to-date than the default provided by the software manager
sudo apt-get update
sudo apt-get install git-all

# wget -O ~/.git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh # For git info in terminal prompt (not needed, seems to be pre-installed)

printf "\n--------------------\n"
printf "Installing tmux"
printf "\n--------------------\n"
sudo add-apt-repository ppa:pi-rho/dev
sudo apt-get update
sudo apt-get install tmux-next

printf "\n--------------------\n"
printf "Configuring git"
printf "\n--------------------\n"
echo -n "Please enter your name (for git config): "
read name
git config --global user.name "$name"
echo -n "Please enter your email (for git config): "
read email
git config --global user.email "$email"
git config --global core.editor vim		    # If you don't want vim, change this to your preferred editor

git config --global alias.co "checkout"     # If you don't want these git aliases, comment them out
git config --global alias.b "branch"
git config --global alias.st "status"
git config --global alias.rso "remote show origin"
git config --global alias.rpo "remote prune origin"
git config --global alias.rao "remote add origin"
git config --global alias.d "diff"
git config --global alias.dc "diff --cached"
git config --global alias.lg "log --all --decorate --oneline --graph"

printf "\n--------------------\n"
printf "Installing libsecret (git credential helper)"
printf "\n--------------------\n"
sudo apt-get install libsecret-1-0 libsecret-1-dev
sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret 
# git config --global credential.helper cache	# If you don't want credentials to be stored permanently, use this instead

printf "\n--------------------\n"
printf "Installing go"
printf "\n--------------------\n"
wget -P ~/Downloads https://dl.google.com/go/go1.11.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf ~/Downloads/go1.11.linux-amd64.tar.gz
mkdir ~/go ~/go/bin ~/go/pkg ~/go/src   # If you want your go workspace in a non-standard location, change this
export PATH=$PATH:/usr/local/go/bin     # Not permament unless set in $HOME/.profile, but necessary for :GoInstallBinaries to work (see below)
# export GOPATH=~/go 			        # Not necessary unless go workspace is in a non-standard location

printf "\n--------------------\n"
printf "Installing golang.org/x/tools"
printf "\n--------------------\n"
go get -u golang.org/x/tools/...

printf "\n--------------------\n"
printf "Installing govendor"
printf "\n--------------------\n"
go get -u github.com/kardianos/govendor

printf "\n--------------------\n"
printf "Installing dep"
printf "\n--------------------\n"
go get -u github.com/golang/dep/cmd/dep

printf "\n--------------------\n"
printf "Installing graphviz"
printf "\n--------------------\n"
sudo apt-get install graphviz   # For visualizing dependency graphs - see: https://github.com/golang/dep#visualizing-dependencies

printf "\n--------------------\n"
printf "Installing vim-tmux-navigator"
printf "\n--------------------\n"
git clone https://github.com/christoomey/vim-tmux-navigator ~/.vim/pack/plugins/start/vim-tmux-navigator

printf "\n--------------------\n"
printf "Installing vim-go"
printf "\n--------------------\n"
git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go
vim +GoInstallBinaries +qall			    # Opens vim temporarily to run the :GoInstallBinaries command, then closes it

printf "\n--------------------\n"
printf "Installing vim-javascript"
printf "\n--------------------\n"
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/pack/plugins/start/vim-javascript

printf "\n--------------------\n"
printf "Installing vim-jsx"
printf "\n--------------------\n"
git clone https://github.com/mxw/vim-jsx.git ~/.vim/pack/plugins/start/vim-jsx

printf "\n--------------------\n"
printf "Installing vim-git-gutter"
printf "\n--------------------\n"

git clone https://github.com/airblade/vim-gitgutter.git ~/.vim/pack/plugins/start/vim-gitgutter

printf "\n--------------------\n"
printf "Installing vim-fugitive"
printf "\n--------------------\n"

git clone https://github.com/tpope/vim-fugitive.git ~/.vim/pack/plugins/start/vim-fugitive
vim -u NONE -c "helptags ~/.vim/pack/plugins/start/vim-fugitive/doc" -c q

printf "\n--------------------\n"
printf "Installing targets.vim"
printf "\n--------------------\n"

git clone https://github.com/wellle/targets.vim.git ~/.vim/pack/plugins/start/targets.vim

printf "\n--------------------\n"
printf "Installing vim-surround"
printf "\n--------------------\n"

git clone https://github.com/tpope/vim-surround.git ~/.vim/pack/plugins/start/vim-surround
vim -u NONE -c "helptags ~/.vim/pack/plugins/start/vim-surround/doc" -c q

printf "\n--------------------\n"
printf "Installing vim-repeat"
printf "\n--------------------\n"

git clone https://github.com/tpope/vim-repeat.git ~/.vim/pack/plugins/start/vim-repeat

printf "\n--------------------\n"
printf "Installing ultisnips"
printf "\n--------------------\n"

git clone https://github.com/sirver/ultisnips ~/.vim/pack/plugins/start/ultisnips

printf "\n--------------------\n"
printf "Installing vim-dadbod"
printf "\n--------------------\n"

git clone https://github.com/tpope/vim-dadbod.git ~/.vim/pack/plugins/start/vim-dadbod
vim -u NONE -c "helptags ~/.vim/pack/plugins/start/vim-dadbod/doc" -c q

printf "\n--------------------\n"
printf "Installing vim-airline"
printf "\n--------------------\n"

git clone https://github.com/vim-airline/vim-airline.git ~/.vim/pack/plugins/start/vim-airline
git clone https://github.com/nathanjcochran/vim-airline-themes ~/.vim/pack/plugins/start/vim-airline-themes

printf "\n--------------------\n"
printf "Installing vim-colors-solarized"
printf "\n--------------------\n"
git clone https://github.com/altercation/vim-colors-solarized.git ./.vim/pack/plugins/start/vim-colors-solarized

printf "\n--------------------\n"
printf "Installing gnome terminal solarized"
printf "\n--------------------\n"
sudo apt-get install dconf-cli              # Vim solarized colors only work if terminal is also solarized. See: https://github.com/altercation/vim-colors-solarized#important-note-for-terminal-users
cd ~
git clone https://github.com/Anthony25/gnome-terminal-colors-solarized.git
cd gnome-terminal-colors-solarized
./install.sh -s dark --install-dircolors    # This will walk the user through the process, and they can abort if they want to
mv ~/.dir_colors/dircolors ~/.dircolors     # See note at bottom: https://github.com/seebi/dircolors-solarized#general-instructions
rm -r ~/.dir_colors

printf "\n--------------------\n"
printf "Installing tmuxline"
printf "\n--------------------\n"
git clone https://github.com/edkolev/tmuxline.vim.git ~/.vim/pack/plugins/start/tmuxline
vim +TmuxlineSnapshot\!\ .tmuxline.conf +qall # Might need to run this again after putting .vimrc in place

printf "\n--------------------\n"
printf "Installing postgreSQL"
printf "\n--------------------\n"
wget -q -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - # See: https://www.postgresql.org/download/linux/ubuntu/
line='deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'
file='/etc/apt/sources.list.d/pgdg.list'
grep -q -F "$line" $file || sudo sh -c "echo \"$line\" >> $file" # Only add line if it doesn't already exist
sudo apt-get update
sudo apt-get install postgresql-9.6 		# May need to update version number
sudo apt-get install postgresql-contrib-9.6

echo -n "Please enter password for default postgres user: "
read password
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '$password'"

# Create postgres user with same name as operating system user (makes
# local login via IDENT authentication possible - in pgAdminIII, you must
# leave host and password blank, and set username to your username).
# NOTE: Decided to set password for default postgres user instead,
# because clients connecting over TCP/IP need to use password
# authentication anyways (IDENT only works locally):
#user=$USER
#sudo -u postgres createuser -s $user    

printf "\n--------------------\n"
printf "Installing pgAdmin"
printf "\n--------------------\n"
sudo apt-get install pgadmin3			# People seem to prefer pgadmin3 over pgadmin4

printf "\n--------------------\n"
printf "Installing mssql-tools"
printf "\n--------------------\n"
wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
line=$(wget -q -O - https://packages.microsoft.com/config/ubuntu/16.04/prod.list)
file='/etc/apt/sources.list.d/msprod.list'
grep -q -F "$line" $file || sudo sh -c "echo \"$line\" >> $file" # Only add line if it doesn't already exist
sudo apt-get update 
sudo apt-get install mssql-tools unixodbc-dev

printf "\n--------------------\n"
printf "Installing dbeaver"
printf "\n--------------------\n"
wget -P ~/Downloads https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb # May need to update at some point (visit dbeaver download page to find link)
sudo apt-get install ~/Downloads/dbeaver-ce_latest_amd64.deb

printf "\n--------------------\n"
printf "Installing docker"
printf "\n--------------------\n"
# See: https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
# And: https://docs.docker.com/install/linux/linux-postinstall/
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
wget -q -O - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
sudo apt-get update
sudo apt-get install docker-ce
# sudo groupadd docker
sudo usermod -aG docker $USER
sudo systemctl enable docker

printf "\n--------------------\n"
printf "Installing kafka"
printf "\n--------------------\n"
wget -P ~/Downloads http://us.mirrors.quenda.co/apache/kafka/1.1.1/kafka_2.11-1.1.1.tgz
tar -xvzf ~/Downloads/kafka_2.11-1.0.0.tgz -C ~/
mv ~/kafka_2.11-1.0.0 ~/kafka

printf "\n--------------------\n"
printf "Installing firefox"    
printf "\n--------------------\n"
sudo add-apt-repository ppa:mozillateam/firefox-next
sudo apt-get update
sudo apt install firefox

printf "\n--------------------\n"
printf "Installing chrome"    
printf "\n--------------------\n"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - # See: https://askubuntu.com/a/510186
line='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
file='/etc/apt/sources.list.d/google-chrome.list'
grep -q -F "$line" $file || sudo sh -c "echo \"$line\" >> $file" # Only add line if it doesn't already exist
sudo apt-get update 
sudo apt-get install google-chrome-stable

printf "\n--------------------\n"
printf "Installing postman"
printf "\n--------------------\n"
wget -O ~/Downloads/postman.tar.gz https://dl.pstmn.io/download/latest/linux64 # See: https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/
sudo tar -xzf ~/Downloads/postman.tar.gz -C /opt
sudo ln -s /opt/Postman/Postman /usr/bin/postman

printf "\n--------------------\n"
printf "Installing slack"
printf "\n--------------------\n"
wget -P ~/Downloads https://downloads.slack-edge.com/linux_releases/slack-desktop-2.8.0-amd64.deb # May need to update version number (visit slack download page to find it)
sudo apt-get install ~/Downloads/slack-desktop-2.8.0-amd64.deb

printf "\n--------------------\n"
printf "Installing spotify"
printf "\n--------------------\n"
sudo apt-get install spotify-client

printf "\n--------------------\n"
printf "Installing shutter"
printf "\n--------------------\n"
sudo add-apt-repository ppa:shutter/ppa
sudo apt-get update
sudo apt-get install shutter
sudo apt-get install libgoo-canvas-perl # Enables editing screenshots
sudo apt-get install gnome-web-photo    # Enables capturing web pages

printf "\n--------------------\n"
printf "Installing peek"
printf "\n--------------------\n"
sudo add-apt-repository ppa:peek-developers/stable
sudo apt-get update
sudo apt-get install peek

printf "\n--------------------\n"
printf "Installing inotify-tools"
printf "\n--------------------\n"
sudo apt-get install inotify-tools

printf "\n--------------------\n"
printf "Installing hub"
printf "\n--------------------\n"
go get github.com/github/hub

printf "\n--------------------\n"
printf "Installing rvm and ruby 2.3.4"
printf "\n--------------------\n"
sudo gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
sudo curl -sSL https://get.rvm.io | sudo bash -s stable --ruby=2.3.4

printf "\n--------------------\n"
printf "Installing pip and virtualenv"
printf "\n--------------------\n"
sudo apt-get install python-pip python-dev build-essential 
sudo pip install --upgrade pip 
sudo pip install --upgrade virtualenv 

printf "\n--------------------\n"
printf "Installing grip"
printf "\n--------------------\n"
sudo pip install setuptools
sudo pip install grip

printf "\n--------------------\n"
printf "Installing google-cloud-sdk"
printf "\n--------------------\n"
wget -P ~/Downloads https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-180.0.0-linux-x86_64.tar.gz
tar -xvzf ~/Downloads/google-cloud-sdk-180.0.0-linux-x86_64.tar.gz -C ~/
~/google-cloud-sdk/install.sh
~/google-cloud-sdk/bin/gcloud init
~/google-cloud-sdk/bin/gcloud components install app-engine-go
~/google-cloud-sdk/bin/gcloud components update

printf "\n--------------------\n"
printf "Installing VirtualBox"
printf "\n--------------------\n"
wget -P ~/Downloads https://download.virtualbox.org/virtualbox/5.2.20/virtualbox-5.2_5.2.20-125813~Ubuntu~xenial_amd64.deb # May need to update at some point (visit VirtualBox download page to find link)
sudo apt-get install ~/Downloads/virtualbox-5.2_5.2.20-125813~Ubuntu~xenial_amd64.deb

printf "\n--------------------\n"
printf "Installing VirtualBox Extension Pack"
printf "\n--------------------\n"
wget -P ~/Downloads https://download.virtualbox.org/virtualbox/5.2.14/Oracle_VM_VirtualBox_Extension_Pack-5.2.14.vbox-extpack
virtualbox ~/Downloads/Oracle_VM_VirtualBox_Extension_Pack-5.2.14.vbox-extpack

printf "\n--------------------\n"
printf "Installing Vagrant"
printf "\n--------------------\n"
wget -P ~/Downloads https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb
sudo apt-get install ~/Downloads/vagrant_2.1.2_x86_64.deb

go_projects=(					# May need to add/remove projects
        account
        algolia-indexer
        auth
        backpack
        data-transfer
        detail-management
        dynamic-fact-transporter
        dynamic-list-transporter
        editorial
        enliten
        entity
        entity-transporter
        fact
        fact-transporter
        featured
        global-nav
        go-common
        grade
        hydration
        juice
        lead
        legacy-new-world
        list
        loadtest
        mail
        map
        metadata
        mock-service
        partner
        photo
        photo-uploader
        premium
        profile
        qprof
        realtorcomlocator
        scatterplot
        scatterplot-transporter
        scholarship
        scholarship-deadliner
        scholarship-indexer
        search
        survey
        urlinator
)

export GIT_TERMINAL_PROMPT=1			# So git will prompt for credentials, instead of failing
for go_project in "${go_projects[@]}"; do
	printf "\n--------------------\n"
	printf "Installing $go_project"
	printf "\n--------------------\n"
	go get -u -v "github.com/nicheinc/$go_project"
done

# Create symbolic link in home directory to nicheinc directory
ln -s ~/go/src/github.com/nicheinc/

printf "\n--------------------\n"
printf "Installing nvm"
printf "\n--------------------\n"
wget -q -O - https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash # May need to update version number
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

printf "\n--------------------\n"
printf "Installing node.js"
printf "\n--------------------\n"
nvm install 6.11.2

printf "\n--------------------\n"
printf "Installing nodemon"
printf "\n--------------------\n"
npm install -g nodemon

printf "\n--------------------\n"
printf "Installing doctoc"
printf "\n--------------------\n"
npm install -g doctoc

printf "\n--------------------\n"
printf "Installing Website"
printf "\n--------------------\n"
mkdir ~/js					# If you want the Website code to live in a different directory, change this
cd ~/js
git clone https://github.com/nicheinc/Website.git

if [ ! -f ~/.ssh/id_rsa ]; then
	# See: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
	printf "Generating ssh key required for github.com/nicheinc dependencies\n"
	ssh-keygen -t rsa -b 4096 -C "$email" -f ~/.ssh/id_rsa -N ''
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/id_rsa
	sudo apt-get install xclip
	xclip -sel clip < ~/.ssh/id_rsa.pub
	google-chrome https://github.com/settings/keys
	printf "\n--------------------\n"
	printf "NOTE: Please log in to github.com, click 'New SSH Key', and paste into the 'Key' textbox (the ssh key has already been copied to your clipboard)\n"
	printf "NOTE: You may give the key any descriptive name you want (e.g. niche-linux)\n"
	printf "NOTE: Once finished, press [Enter] to continue"
	read -s
fi

cd ~/js/Website
npm install
# npm run dev 					# This would run webpack, but webpack is in watch mode by default in dev, due to webpack.config.json, so it would hang indefinately :/

printf "\n--------------------\n"
printf "Cleaning up unused dependencies"
printf "\n--------------------\n"
sudo apt-get autoremove

printf "\n--------------------\n"
printf "Creating $HOME/bin directory"
printf "\n--------------------\n"
mkdir ~/bin

printf "\n--------------------\n"
printf "Fetching .vimrc, .bashrc, and .profile"
printf "\n--------------------\n"

wget -O ~/.vimrc - https://raw.githubusercontent.com/cochran-at-niche/home/master/.vimrc
wget -O ~/.bashrc - https://raw.githubusercontent.com/cochran-at-niche/home/master/.bashrc
wget -O ~/.profile - https://raw.githubusercontent.com/cochran-at-niche/home/master/.profile
wget -O ~/.tmux.conf - https://raw.githubusercontent.com/cochran-at-niche/home/master/.tmux.conf
wget -O ~/.tmuxline.conf - https://raw.githubusercontent.com/cochran-at-niche/home/master/.tmuxline.conf
